2025-04-07 01:03:46.588 | WARNING  | qlib.tests.data:qlib_data:195 - Data already exists: ~/QuantProject/.qlib/qlib_data/cn_data, the data download will be skipped
	If downloading is required: `exists_skip=False` or `change target_dir`
[2743709:MainThread](2025-04-07 01:03:46,589) INFO - qlib.Initialization - [config.py:420] - default_conf: client.
[2743709:MainThread](2025-04-07 01:03:46,591) INFO - qlib.Initialization - [__init__.py:74] - qlib successfully initialized based on client settings.
[2743709:MainThread](2025-04-07 01:03:46,591) INFO - qlib.Initialization - [__init__.py:76] - data_path={'__DEFAULT_FREQ': PosixPath('/home/24039378g/QuantProject/.qlib/qlib_data/cn_data')}

模型参数量统计:
--------------------------------------------------
特征门控层 (Gate): 10,112 参数
输入映射层 (x2y): 40,704 参数
时间注意力层 (TAttention): 329,216 参数
空间注意力层 (SAttention): 329,216 参数
时序注意力层 (TemporalAttention): 65,536 参数
解码器 (Decoder): 257 参数
--------------------------------------------------
总参数量: 775,041
[2743709:MainThread](2025-04-07 01:05:30,622) INFO - qlib.timer - [log.py:127] - Time cost: 102.797s | Loading data Done
/home/24039378g/.conda/envs/MASTER/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1217: RuntimeWarning: All-NaN slice encountered
  return function_base._ureduce(a, func=_nanmedian, keepdims=keepdims,
[2743709:MainThread](2025-04-07 01:05:33,967) INFO - qlib.timer - [log.py:127] - Time cost: 3.120s | RobustZScoreNorm Done
[2743709:MainThread](2025-04-07 01:05:34,334) INFO - qlib.timer - [log.py:127] - Time cost: 0.367s | Fillna Done
[2743709:MainThread](2025-04-07 01:05:34,577) INFO - qlib.timer - [log.py:127] - Time cost: 0.139s | DropnaLabel Done
/home/24039378g/QuantProject/QLIB/qlib/data/dataset/processor.py:370: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols] = t
[2743709:MainThread](2025-04-07 01:05:34,784) INFO - qlib.timer - [log.py:127] - Time cost: 0.206s | CSRankNorm Done
[2743709:MainThread](2025-04-07 01:05:34,786) INFO - qlib.timer - [log.py:127] - Time cost: 4.163s | fit & process data Done
[2743709:MainThread](2025-04-07 01:05:34,786) INFO - qlib.timer - [log.py:127] - Time cost: 106.961s | Init data Done
[2743709:MainThread](2025-04-07 01:06:01,830) INFO - qlib.timer - [log.py:127] - Time cost: 27.018s | Loading data Done
[2743709:MainThread](2025-04-07 01:06:02,629) INFO - qlib.timer - [log.py:127] - Time cost: 0.769s | RobustZScoreNorm Done
[2743709:MainThread](2025-04-07 01:06:02,714) INFO - qlib.timer - [log.py:127] - Time cost: 0.084s | Fillna Done
[2743709:MainThread](2025-04-07 01:06:02,726) INFO - qlib.timer - [log.py:127] - Time cost: 0.895s | fit & process data Done
[2743709:MainThread](2025-04-07 01:06:02,726) INFO - qlib.timer - [log.py:127] - Time cost: 27.915s | Init data Done
[2743709:MainThread](2025-04-07 01:06:02,741) INFO - qlib.workflow - [exp.py:258] - Experiment 566184983307789232 starts running ...
[2743709:MainThread](2025-04-07 01:06:02,852) INFO - qlib.workflow - [recorder.py:345] - Recorder bff73d78fac74332acd9d14146e45024 starts running under Experiment 566184983307789232 ...
[2743709:MainThread](2025-04-07 01:23:07,886) INFO - qlib.workflow - [exp.py:258] - Experiment 362767161650010529 starts running ...
Epoch 0, train_loss 1.063945, valid_loss 0.998334 
Epoch 1, train_loss 1.012205, valid_loss 0.988457 
Epoch 2, train_loss 0.997635, valid_loss 0.985167 
Epoch 3, train_loss 0.991656, valid_loss 0.983436 
Epoch 4, train_loss 0.987644, valid_loss 0.985438 
Epoch 5, train_loss 0.984832, valid_loss 0.984021 
Epoch 6, train_loss 0.982386, valid_loss 0.981904 
Epoch 7, train_loss 0.980066, valid_loss 0.983205 
Epoch 8, train_loss 0.978744, valid_loss 0.981032 
Epoch 9, train_loss 0.975915, valid_loss 0.983403 
Epoch 10, train_loss 0.974595, valid_loss 0.982881 
Epoch 11, train_loss 0.972746, valid_loss 0.981754 
Epoch 12, train_loss 0.971239, valid_loss 0.984201 
Epoch 13, train_loss 0.969612, valid_loss 0.984815 
Epoch 14, train_loss 0.967702, valid_loss 0.982607 
Epoch 15, train_loss 0.966176, valid_loss 0.985325 
Epoch 16, train_loss 0.964575, valid_loss 0.989429 
Epoch 17, train_loss 0.963935, valid_loss 0.984347 
Epoch 18, train_loss 0.961397, valid_loss 0.985690 
Epoch 19, train_loss 0.960380, valid_loss 0.985513 
Epoch 20, train_loss 0.958776, valid_loss 0.988756 
Epoch 21, train_loss 0.956791, valid_loss 0.991020 
Epoch 22, train_loss 0.956053, valid_loss 0.990610 
Epoch 23, train_loss 0.955018, valid_loss 0.989836 
Epoch 24, train_loss 0.952606, valid_loss 0.992296 
Epoch 25, train_loss 0.951170, valid_loss 0.992271 
Epoch 26, train_loss 0.950123, valid_loss 0.995021 
Epoch 27, train_loss 0.948398, valid_loss 0.993984 
[STATUS]: MODEL TRAINING/ LOADING FINISHED
[2743709:MainThread](2025-04-07 01:23:07,892) ERROR - qlib.workflow - [utils.py:41] - An exception has been raised[Exception: Run with UUID bff73d78fac74332acd9d14146e45024 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True].
  File "/home/24039378g/QuantProject/QLIB/examples/workflow_by_code.py", line 195, in <module>
    with R.start(experiment_name="backtest_analysis"):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/24039378g/.conda/envs/MASTER/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/24039378g/QuantProject/QLIB/qlib/workflow/__init__.py", line 69, in start
    run = self.start_exp(
          ^^^^^^^^^^^^^^^
  File "/home/24039378g/QuantProject/QLIB/qlib/workflow/__init__.py", line 125, in start_exp
    return self.exp_manager.start_exp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/24039378g/QuantProject/QLIB/qlib/workflow/expm.py", line 86, in start_exp
    return self._start_exp(
           ^^^^^^^^^^^^^^^^
  File "/home/24039378g/QuantProject/QLIB/qlib/workflow/expm.py", line 345, in _start_exp
    self.active_experiment.start(recorder_id=recorder_id, recorder_name=recorder_name, resume=resume)
  File "/home/24039378g/QuantProject/QLIB/qlib/workflow/exp.py", line 271, in start
    self.active_recorder.start_run()
  File "/home/24039378g/QuantProject/QLIB/qlib/workflow/recorder.py", line 339, in start_run
    run = mlflow.start_run(self.id, self.experiment_id, self.name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/24039378g/.conda/envs/MASTER/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 351, in start_run
    raise Exception(
Exception: Run with UUID bff73d78fac74332acd9d14146e45024 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True
